//===================================================================
// COPYRIGHT General Electric 2018/05/28
//===================================================================
// CAABatch.cpp
// Header definition of class CAABatch
//===================================================================
//
// Usage notes:
//
//===================================================================
//  2018/05/28 Creation: Code generated by the 3DS wizard
//===================================================================
#ifndef ExportedByCAABatch_H
#define ExportedByCAABatch_H
#if defined(__CAABatch)
# define ExportedByCAABatch   DSYExport
#else // __CAABatch
# define ExportedByCAABatch   DSYImport
#endif  // __CAABatch
#else //ExportedByCAABatch_H

#include "DSYExport.h"

#endif //ExportedByCAABatch_H

